# Newton Optimization


This notebook has an example of Neton Optimization tecnique on a Multilayer Perceptron using NumPy.


but first wee need to undestand what is a Newton Optimization Technique and how is it dfferent from the Gradient Descent Tecnique gernally used for optimizing a Neural Network.

In [1]:
import numpy as np

# Single Perceptron

In [2]:
# Here I am building a normal forward propogation for a single perceptron
# and the various function i would use.

In [3]:
def sigmoid(z):
    #this is the non-linear activation function
    return (1 / (1 + np.exp(-z)))

In [4]:
#############################################
## Declaring Traing Data        ############
#############################################
X_train = np.array([[0,0],[1,0],[0,1],[1,1]])
Y_train = np.array([[1],[0],[0],[1]])



In [5]:
class Loss:
    '''
    Class containing loss functions
    '''
    
    def __init__(self):
        return
    
    def sq_loss(self , pred ,Y):
        loss = Y - pred
        d_loss = -1 * 2 * loss
        loss = np.sum(loss * loss)
        
        return loss,d_loss
    

In [6]:
class Neural_Layer:
    '''
    This is a very specefic Neuron class that uses sigmoid activation
    and square loss.
    '''
    def __init__(self,l0,l1):
        self.W = np.random.randn(l0 ,l1) * np.sqrt(2.0 /l0 )
        self.b = np.zeros((l1))
        print(self.W.shape , self.b.shape)
        
    def forward(self,X):
        #print(X.shape , self.W.shape , self.b.shape)
        h_x = X.dot(self.W) + self.b
        h_x = sigmoid(h_x)
        return h_x
    
    def update_newton(self,X,h_x,d_back):
        
        #f_x = self.forward(X) 
        f_x = h_x
        
        #Dirivating w.r.t W
        temp = f_x * (1 - f_x) * d_back #this value was computed again and again
        f_x_dash_W = X.T.dot(temp)
        f_x_dash_dash_W = (X.T.dot(1 - (2 * f_x))) * f_x_dash_W
        
        #Derivatng w.r.t b
        f_x_dash_b = temp
        f_x_dash_dash_b = f_x * (1 - 2 * f_x_dash_b)
        
        #Derivating w.r.t x(to return to previous layers)
        f_x_dash_x = temp.dot(self.W.T)   
        
        delta_W = -1 * (f_x_dash_W / f_x_dash_dash_W)
        self.W = self.W + delta_W
        
        delta_b = -1 * np.sum(f_x_dash_b / f_x_dash_dash_b , axis = 0)
        self.b = self.b + delta_b
        
        d_back = f_x_dash_x
        
        return d_back
        
    def update_batch_gradient_descent(self , X , h_x , d_back,alpha = 0.01):
        
        f_x = h_x
        
        temp = f_x * (1 - f_x) * d_back
        #Dirivating w.r.t W
        f_x_dash_W = X.T.dot(temp)
        
        #Derivatng w.r.t b
        f_x_dash_b = temp
        
        #Derivating w.r.t x(to return to previous layers)
        f_x_dash_x = temp.dot(self.W.T)
        
        #Update W
        delta_W = f_x_dash_W
        self.W = self.W - alpha * delta_W
        
        #Update b
        delta_b = np.sum(f_x_dash_b , axis =0)
        self.b = self.b - alpha * delta_b
        
        d_back = f_x_dash_x
        return d_back
           

In [7]:
def accuracy(model , X , Y):
    pred = model.forward(X)
    pred =pred > 0.5
    acc = np.sum(pred == Y)
    acc = acc / Y.shape[0]
    return acc

In [8]:
# Declare a neuron with shape of weights as [shape_of_input,1]
model = Neural_Layer(2,1)
loss_m = Loss()

(2, 1) (1,)


In [9]:
# testing the model outputs
model.forward(X_train)

array([[0.5       ],
       [0.67857825],
       [0.76411289],
       [0.87242896]])

In [10]:
# Now we can train the model by training on a batch.As our batch is equal to the raing data.1 iter = 1 epoch


def train_newton_update(model ,loss_m,X_train , Y_train,epochs):
    for i in range(epochs):
        h_x = model.forward(X_train)
        loss,d_loss = loss_m.sq_loss(h_x,Y_train)
        acc = accuracy(model ,X_train,Y_train)
        print("The training loss at {}th epoch : {}  Training Accuracy:{}".format(i , loss , acc))
        
        model.update_newton(X_train,h_x , d_loss)        

train_newton_update(model , loss_m , X_train,Y_train , 10)
    

The training loss at 0th epoch : 1.3106113195202735  Training Accuracy:0.25
The training loss at 1th epoch : 1.3438342091441138  Training Accuracy:0.25
The training loss at 2th epoch : 1.443314375929998  Training Accuracy:0.25
The training loss at 3th epoch : 1.7301217110075013  Training Accuracy:0.25
The training loss at 4th epoch : 1.8885918079033581  Training Accuracy:0.25
The training loss at 5th epoch : 2.1346740465999874  Training Accuracy:0.25
The training loss at 6th epoch : 2.5371416633133386  Training Accuracy:0.25
The training loss at 7th epoch : 2.812321370831639  Training Accuracy:0.25
The training loss at 8th epoch : 2.6509277119898798  Training Accuracy:0.25
The training loss at 9th epoch : 2.414860258262007  Training Accuracy:0.25


In [11]:
# Now we can predict the values for unseen data or trained data also
# We can also calculate the accuracy of the model we have trained
accuracy(model , X_train,Y_train)

0.25

In [12]:
model = Neural_Layer(2,1)
loss_m = Loss()

def train_gradient_update(model ,loss_m,X_train , Y_train,epochs):
    for i in range(epochs):
        h_x = model.forward(X_train)
        loss,d_loss = loss_m.sq_loss(h_x,Y_train)
        acc = accuracy(model ,X_train,Y_train)
        print("The training loss at {}th epoch : {}  Training Accuracy:{}".format(i , loss , acc))
        
        model.update_batch_gradient_descent(X_train,h_x , d_loss , 0.01)        

train_newton_update(model , loss_m , X_train,Y_train , 10)
    

(2, 1) (1,)
The training loss at 0th epoch : 1.1101920569652854  Training Accuracy:0.25
The training loss at 1th epoch : 1.479373641896645  Training Accuracy:0.25
The training loss at 2th epoch : 1.4425253176135537  Training Accuracy:0.25
The training loss at 3th epoch : 1.7456017414542437  Training Accuracy:0.25
The training loss at 4th epoch : 1.9063977163803227  Training Accuracy:0.25
The training loss at 5th epoch : 2.1628098036600067  Training Accuracy:0.25
The training loss at 6th epoch : 2.57444484423525  Training Accuracy:0.25
The training loss at 7th epoch : 2.8112514361582925  Training Accuracy:0.25
The training loss at 8th epoch : 2.625739273936632  Training Accuracy:0.25
The training loss at 9th epoch : 2.397586951638596  Training Accuracy:0.25


In [13]:
# Now we can predict the values for unseen data or trained data also
# We can also calculate the accuracy of the model we have trained
accuracy(model , X_train,Y_train)

0.25

# Neural Network

Now that we have built a single perceptron layer we can scale it to make a neural net(A deep Neral Net would just be adding more layers on it)

We will try to make a Neural Network that is scalable from scratch.That is it can be directly used as a library.

In [14]:
class Neural_Net:
    
    def __init__(self , layer_list):
        
        
        self.hidden_layers = len(layer_list) - 1
        
        self.layers = {}
        
        for i in range(self.hidden_layers):            
            self.layers[i+1] = Neural_Layer(layer_list[i] , layer_list[i+1])
            
            
    def forward(self , X_train):
        t = X_train
        cache = []
        cache.append(t)        
        for i in range(self.hidden_layers):
            t = self.layers[i+1].forward(t)
            cache.append(t)
            
        return t,cache
    
    def update_newton(self , cache, d_back):
        #list of activations--cache
        
        for i in range(self.hidden_layers , 0 , -1):
            d_back = self.layers[i].update_newton(cache[i-1],cache[i],d_back)
            
        return d_back 
    
    def update_gradient(self , cache, d_back , alpha=0.01):
        for i in range(self.hidden_layers , 0 , -1):
            d_back = self.layers[i].update_batch_gradient_descent(cache[i-1],cache[i],d_back,alpha)
            
        return d_back 
            

In [15]:
def accuracy_neural_net(model , X , Y):
    pred,_ = model.forward(X)
    pred =pred > 0.5
    acc = np.sum(pred == Y)
    acc = acc / Y.shape[0]
    return acc

In [16]:
# Lets make a neural net as follows
# visible_layer-->3 neurons-->1 neuron
layer_list = [2 , 4,2 , 1]
model = Neural_Net(layer_list)
loss_m = Loss()

(2, 4) (4,)
(4, 2) (2,)
(2, 1) (1,)


In [17]:
pred,_ = model.forward(X_train)
pred

array([[0.59624879],
       [0.57570382],
       [0.62992417],
       [0.60762873]])

In [18]:
def train_newton_update(model ,loss_m,X_train , Y_train,epochs):
    for i in range(epochs):
        act , cache = model.forward(X_train)
        loss,d_back = loss_m.sq_loss(act,Y_train)
        acc = accuracy_neural_net(model ,X_train,Y_train)
        print("The training loss at {}th epoch : {}  Training Accuracy:{}".format(i , loss , acc))
        model.update_newton(cache,d_back)        

train_newton_update(model , loss_m , X_train,Y_train , 2)
    

The training loss at 0th epoch : 1.0452096025974364  Training Accuracy:0.5
The training loss at 1th epoch : 1.185441402352394  Training Accuracy:0.5


In [19]:
accuracy_neural_net(model,X_train, Y_train)

0.5

In [20]:
layer_list = [2 ,2,2, 1]
model = Neural_Net(layer_list)
loss_m = Loss()

def train_gradient_update(model ,loss_m,X_train , Y_train,epochs,alpha =0.01):
    for i in range(epochs):
        act , cache = model.forward(X_train)
        loss,d_back = loss_m.sq_loss(act,Y_train)
        acc = accuracy_neural_net(model ,X_train,Y_train)
        print("The training loss at {}th epoch : {}  Training Accuracy:{}".format(i , loss , acc))
        model.update_gradient(cache,d_back,alpha)        

train_gradient_update(model , loss_m , X_train,Y_train , 2)

(2, 2) (2,)
(2, 2) (2,)
(2, 1) (1,)
The training loss at 0th epoch : 1.0338127587302044  Training Accuracy:0.5
The training loss at 1th epoch : 1.033147473506944  Training Accuracy:0.5


In [21]:
pred,_ = model.forward(X_train)
pred

array([[0.58515536],
       [0.60871105],
       [0.5778231 ],
       [0.60504627]])

In [22]:
accuracy_neural_net(model,X_train, Y_train)

0.5

# N Bit XOR

Now Lets try working with just a little better data. A n XOR operator. So lets create the dataset for n bit xor.

We would have atmost 2^n data point in this type of data set.BUt we would limit our dataset to a 1000 data points
whichever is smaller.

Then we can divide into training and test set

In [23]:

n = 10
max_datapoint = 1000
datapoints = min(pow(2,n) , max_datapoint)

X = np.zeros((datapoints , n) , dtype=np.int32)
Y = np.zeros((datapoints , 1), dtype=np.int32)

for i in range(datapoints):
    tmp = i
    y_tmp = 0
    for j in range(n-1 , -1 , -1):
        X[i,j] = tmp&1
        y_tmp = y_tmp^X[i,j]
        tmp = tmp>>1
    Y[i] = y_tmp
        
        

In [24]:
# for sanity check lets print one example
ind = 3
print(X[ind] , Y[ind])

[0 0 0 0 0 0 0 0 1 1] [0]


In [25]:
# Lets divide the set in training and testing
div = 0.9
train_n = int(div * datapoints)
X_train = X[:train_n]
Y_train = Y[:train_n]

X_test = X[train_n:]
Y_test = Y[train_n:]
Y_test.shape

(100, 1)

In [26]:
layer_list = [n ,8,4,2, 1]
model = Neural_Net(layer_list)
loss_m = Loss()

(10, 8) (8,)
(8, 4) (4,)
(4, 2) (2,)
(2, 1) (1,)


In [27]:
train_gradient_update(model , loss_m , X_train,Y_train , 200)

The training loss at 0th epoch : 231.43765663008276  Training Accuracy:0.5
The training loss at 1th epoch : 230.15033331382855  Training Accuracy:0.5
The training loss at 2th epoch : 228.5914891322086  Training Accuracy:0.5
The training loss at 3th epoch : 227.75048674115249  Training Accuracy:0.5
The training loss at 4th epoch : 226.9178514994976  Training Accuracy:0.5
The training loss at 5th epoch : 226.43296801232856  Training Accuracy:0.5
The training loss at 6th epoch : 226.00542986289054  Training Accuracy:0.5
The training loss at 7th epoch : 225.74247721813376  Training Accuracy:0.5
The training loss at 8th epoch : 225.52675940861195  Training Accuracy:0.5
The training loss at 9th epoch : 225.38875019627397  Training Accuracy:0.5
The training loss at 10th epoch : 225.2807456633013  Training Accuracy:0.5
The training loss at 11th epoch : 225.209654812245  Training Accuracy:0.5
The training loss at 12th epoch : 225.15575800113382  Training Accuracy:0.5011111111111111
The training

The training loss at 164th epoch : 225.0191866716982  Training Accuracy:0.5022222222222222
The training loss at 165th epoch : 225.01913652603827  Training Accuracy:0.5022222222222222
The training loss at 166th epoch : 225.01908658631157  Training Accuracy:0.5022222222222222
The training loss at 167th epoch : 225.01903685135474  Training Accuracy:0.5022222222222222
The training loss at 168th epoch : 225.01898732001268  Training Accuracy:0.5022222222222222
The training loss at 169th epoch : 225.0189379911388  Training Accuracy:0.5022222222222222
The training loss at 170th epoch : 225.01888886359467  Training Accuracy:0.5011111111111111
The training loss at 171th epoch : 225.01883993625003  Training Accuracy:0.5011111111111111
The training loss at 172th epoch : 225.01879120798284  Training Accuracy:0.5011111111111111
The training loss at 173th epoch : 225.01874267767906  Training Accuracy:0.5011111111111111
The training loss at 174th epoch : 225.01869434423259  Training Accuracy:0.5011111

In [28]:
accuracy_neural_net(model,X_test, Y_test)

0.51

In [29]:
train_newton_update(model , loss_m , X_train,Y_train , 2)

The training loss at 0th epoch : 225.017503328151  Training Accuracy:0.4988888888888889
The training loss at 1th epoch : 450.0  Training Accuracy:0.5


In [30]:
accuracy_neural_net(model,X_test, Y_test)

0.5